spring:
  redis:
    host: localhost
    port: 6379

# MyBatis-Plus 多数据源
  datasource:
    dynamic:
      primary: mysql #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        mysql:
          url: jdbc:mysql://localhost:3306/structure?serverTimezone=Asia/Shanghai&useTimeZone=true
          username: root
          password: admin
          driver-class-name: com.mysql.cj.jdbc.Driver
        hive:
          url: jdbc:hive2://your_hive_ip:port/your_database_name
          username: your_username
          password: your_password
          driver-class-name: org.apache.hive.jdbc.HiveDriver

structure:
  async:
    corePoolSize: 10
    maxPoolSize: 100
    queueCapacity: 10
    threadNamePrefix: StructureExecutor-